services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tasktracker-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TaskTracker_StrongP@ssw0rd!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - tasktracker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c 'cat < /dev/null > /dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  # TaskTrackerAPI
  tasktracker-api:
    build: 
      context: ./TaskTrackerAPI
      dockerfile: Dockerfile
    container_name: tasktracker-api
    ports:
      - "5000:8080"
      - "5002:443"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOCKER_ENVIRONMENT=true
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskTracker;User Id=sa;Password=TaskTracker_StrongP@ssw0rd!;TrustServerCertificate=True;
      - AppSettings__TokenKey=your_development_token_key_here_replace_in_production
      - AppSettings__PasswordKey=your_development_password_key_here_replace_in_production
      - AppSettings__DebugKey=DEVELOPMENT_DEBUG_ONLY_7865421
      - SeedData__DefaultPassword=password
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c 'cat < /dev/null > /dev/tcp/localhost/8080' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - api-keys:/app/Keys
    networks:
      - tasktracker-network
    restart: unless-stopped
  
  # Next.js Frontend - COMMENTED OUT FOR MANUAL DEVELOPMENT
  # tasktracker-fe:
  #   build:
  #     context: ./tasktracker-fe
  #     dockerfile: Dockerfile
  #   container_name: tasktracker-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     tasktracker-api:
  #       condition: service_healthy
  #   environment:
  #     # Frontend needs to use localhost URLs since it runs in the browser
  #     - NEXT_PUBLIC_API_URL=http://localhost:5000/api
  #     - NEXT_PUBLIC_SIGNALR_URL=http://localhost:5000/hubs
  #     - NODE_ENV=production
  #     - DOCKER_ENVIRONMENT=true
  #     - NEXT_TELEMETRY_DISABLED=1
  #     # Performance monitoring
  #     - NEXT_PUBLIC_ENABLE_PERFORMANCE_MONITORING=true
  #     - NEXT_PUBLIC_SW_ENABLED=true
  #   networks:
  #     - tasktracker-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 30s

volumes:
  sqlserver-data:
    name: tasktracker-sqlserver-data
  api-keys:
    name: tasktracker-api-keys

networks:
  tasktracker-network:
    name: tasktracker-network
    driver: bridge 
