name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TokenKey: github_actions_test_token_key_1234567890_abcdefghijklmnop
      PasswordKey: github_actions_test_password_key_0987654321_zyxwvutsrqp
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Run unit tests
      run: dotnet test TaskTrackerAPI.UnitTests --no-build --verbosity normal
    
    - name: Run service tests
      run: dotnet test TaskTrackerAPI.ServiceTests --no-build --verbosity normal
    
    - name: Run integration tests
      run: dotnet test TaskTrackerAPI.IntegrationTests --no-build --verbosity normal

  code-coverage:
    runs-on: ubuntu-latest
    needs: build
    env:
      TokenKey: github_actions_test_token_key_1234567890_abcdefghijklmnop
      PasswordKey: github_actions_test_password_key_0987654321_zyxwvutsrqp
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Install dotnet-coverage
      run: dotnet tool install --global dotnet-coverage
    
    - name: Generate coverage report
      run: |
        dotnet-coverage collect 'dotnet test' -f cobertura -o coverage.cobertura.xml
    
    - name: Generate coverage report HTML
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.cobertura.xml
        fail_ci_if_error: true
    
    - name: Upload coverage report HTML
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage-report/ 